/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entite.Utilisateur;
import service.MessageDialog;

/**
 *
 * @author yvesdegboe
 */
public class UtilisateurPan extends javax.swing.JPanel {

    private boolean nouveau = true;
    private Utilisateur currentUtilisateur;

    /**
     * Creates new form UtilisateurPan
     */
    public UtilisateurPan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomfield = new javax.swing.JTextField();
        prenomfield = new javax.swing.JTextField();
        loginfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        typecombo = new javax.swing.JComboBox<>();
        ajoutbtnuser = new javax.swing.JButton();
        nouveaubtnuser = new javax.swing.JButton();
        modifbtnuser = new javax.swing.JButton();
        suppbtnuser = new javax.swing.JButton();
        anbtnuser = new javax.swing.JButton();
        passfield = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(840, 510));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 460));

        jLabel1.setText("Nom");

        jLabel2.setText("Prenoms");

        jLabel3.setText("Login");

        jLabel4.setText("Password");

        jLabel5.setText("Type");

        typecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Comptable" }));

        ajoutbtnuser.setBackground(new java.awt.Color(0, 51, 153));
        ajoutbtnuser.setText("Ajouter");
        ajoutbtnuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutbtnuserActionPerformed(evt);
            }
        });

        nouveaubtnuser.setBackground(new java.awt.Color(0, 51, 153));
        nouveaubtnuser.setText("Nouveau");
        nouveaubtnuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveaubtnuserActionPerformed(evt);
            }
        });

        modifbtnuser.setBackground(new java.awt.Color(0, 51, 153));
        modifbtnuser.setText("Modifier");
        modifbtnuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifbtnuserActionPerformed(evt);
            }
        });

        suppbtnuser.setBackground(new java.awt.Color(0, 51, 153));
        suppbtnuser.setText("Supprimer");

        anbtnuser.setBackground(new java.awt.Color(0, 51, 153));
        anbtnuser.setText("Annuler");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(nomfield)
                        .addComponent(prenomfield)
                        .addComponent(loginfield)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(typecombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ajoutbtnuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nouveaubtnuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modifbtnuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(suppbtnuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anbtnuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(nomfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(prenomfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(loginfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(typecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ajoutbtnuser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nouveaubtnuser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifbtnuser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(suppbtnuser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(anbtnuser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(570, 460));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Login", "Password", "Type"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modifbtnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifbtnuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifbtnuserActionPerformed

    private void ajoutbtnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutbtnuserActionPerformed
        boolean pass = true;
        if (nomfield.getText().equals("")) {
            pass = false;
        }
        if (prenomfield.getText().equals("")) {
            pass = false;
        }
        if (loginfield.getText().equals("")) {
            pass = false;
        }
        if (passfield.getPassword().equals("")) {
            pass = false;
        }

        if (pass) {

            Utilisateur utilisateur = new Utilisateur();

            utilisateur.setNom(nomfield.getText());
            utilisateur.setPrenom(prenomfield.getText());
            utilisateur.setLogin(loginfield.getText());
            utilisateur.setPassword(passfield.getPassword().toString());
            utilisateur.setTypeutilisateur(typecombo.getSelectedItem().toString());

            boolean reponse;

            if (nouveau) {
                reponse = utilisateur.save();

            } else {
                utilisateur = currentUtilisateur;
                utilisateur.setId(currentUtilisateur.getId());
                utilisateur.setNom(nomfield.getText());
                utilisateur.setPrenom(prenomfield.getText());
                utilisateur.setLogin(loginfield.getText());
                utilisateur.setPassword(passfield.getPassword().toString());
                utilisateur.setTypeutilisateur(typecombo.getSelectedItem().toString());
                reponse = utilisateur.update();

            }

            if (reponse) {
                if (nouveau) {
                    MessageDialog.successMessage("ok", "l'Utilisateur " + utilisateur.toString() + " a été créé avec succès");

                } else {
                    MessageDialog.successMessage("ok", "l'Utilisateur " + utilisateur.toString() + " a été mis à jour avec succès");

                }
nomfield.setText("");
prenomfield.setText("");
loginfield.setText("");
passfield.setText("");
typecombo.setSelectedItem("");

            } else {
                MessageDialog.ErrorMessage();
            }
        } else {
            MessageDialog.warningMessage("Attention", "Tous les champs marqués (*) sont obligatoires!");
        }
    }//GEN-LAST:event_ajoutbtnuserActionPerformed

    private void nouveaubtnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveaubtnuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nouveaubtnuserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutbtnuser;
    private javax.swing.JButton anbtnuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField loginfield;
    private javax.swing.JButton modifbtnuser;
    private javax.swing.JTextField nomfield;
    private javax.swing.JButton nouveaubtnuser;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JTextField prenomfield;
    private javax.swing.JButton suppbtnuser;
    private javax.swing.JComboBox<String> typecombo;
    // End of variables declaration//GEN-END:variables
}
